### 1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np
x=np.zeros(10) 
x[4]=1  
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 2. Create a vector with values ranging from 10 to 49.

In [3]:
import numpy as np
v = np.arange(10,50)
print("Array:")
print(v)

Array:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


### 3. Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
import numpy as np
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [8]:
x = np.array([1,2,0,0,4,0])
print(x)
np.nonzero(x)

[1 2 0 0 4 0]


(array([0, 1, 4], dtype=int64),)

### 5.Create a 10x10 array with random values and find the minimum and maximum values.

In [16]:
# exercise 2
a=np.random.random((10,10))
print('Maximum value is: ',a.max())
print('Minimum value is: ',a.min())

Maximum value is:  0.9956045538037112
Minimum value is:  0.011888920360311195


### 6. Create a random vector of size 30 and find the mean value.

In [20]:
g=np.random.random(30)
print("Original Array :\n",g,"\n")
print("Mean of given array",np.mean(g))

Original Array :
 [0.76596791 0.25665945 0.13686997 0.62135192 0.1100182  0.08448907
 0.68397591 0.67054819 0.78744011 0.92754576 0.41813369 0.33313464
 0.89534538 0.471442   0.11975854 0.56231291 0.20005489 0.41511531
 0.36879921 0.89556209 0.05932032 0.99426055 0.17542099 0.82172143
 0.70913005 0.37889966 0.81623774 0.97179713 0.04353196 0.87562977] 

Mean of given array 0.5190158249647713
